name: Contact Us E2E Test
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci --ignore-scripts
      - run: npx lambdatest-cypress-cli run --lcf lambdatest-config-contact-us.json --envs "CYPRESS_QA_BYPASS_TOKEN=$CYPRESS_QA_BYPASS_TOKEN"
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          CYPRESS_QA_BYPASS_TOKEN: ${{ secrets.QA_BYPASS_TOKEN }}
